import type {
  Achievement,
  Certification,
  Experience,
  Post,
  Project,
  Skill,
} from "@/lib/types";

/**
 * Canonical content. The public data layer falls back to this when Supabase
 * is unreachable (or env vars are unset), so the site renders fully static.
 * The admin CRUD and `npm run seed` write the same shape to Postgres.
 */

export const SEED_SETTINGS = {
  heroBadge: "B.E. CSE (Cybersecurity) — Class of 2028",
  resumeUrl: null as string | null,
  email: "prasanthselvaraj1511@gmail.com",
  linkedin: "https://linkedin.com/in/prasanth-selva-1810aa315",
  github: "https://github.com/prasanth-selva",
  phone: null as string | null,
  seoTitle: "Prasanth Selva — Cybersecurity Engineer",
  seoDescription:
    "Portfolio of Prasanth Selva, third-year B.E. CSE (Cybersecurity) student and aspiring cybersecurity engineer: SOC operations, AI-driven threat monitoring, web security and secure systems engineering.",
};

export const SEED_ABOUT = {
  bio: [
    "I'm Prasanth Selva, a third-year B.E. Computer Science & Engineering (Cybersecurity) student at KGISL Institute of Technology, Coimbatore, graduating May 2027. I break things to secure them — from SOC dashboards to web apps, I obsess over how systems fail and how to make that failure boring.",
    "As President of VYUGAM, the Cyber Department Association, I lead a community of builders and breakers: running workshops, capture-the-flag events and security bootcamps for 300+ students. My internships span a SOC floor, a cybercrime police station and a product startup — rare context for an undergraduate, and the reason I think in incidents, not just vulnerabilities.",
    "The goal is a cybersecurity engineering career with an international trajectory: AI-driven detection engineering, offensive tooling, and secure systems that ordinary people can trust.",
  ],
  photo: null as string | null,
  stats: [
    { label: "CGPA", value: 8.09, suffix: "" },
    { label: "Internships", value: 3, suffix: "" },
    { label: "CTF Rankings", value: 2, suffix: "" },
    { label: "Certifications", value: 5, suffix: "" },
  ],
};

export const SEED_PROJECTS: Project[] = [
  {
    id: "seed-cyberthozhan",
    slug: "cyberthozhan",
    title: "CyberThozhan",
    tagline: "AI-powered cyber safety platform for Tamil-speaking users",
    description:
      "CyberThozhan is an AI-powered cyber safety platform that teaches safe internet habits and triages scam reports in Tamil and English. It combines a fine-tuned RAG assistant over curated safety corpora with a reporting pipeline that classifies scam screenshots (OTP fraud, phishing, UPI scams) and routes high-risk cases with actionable guidance. Built with Next.js, FastAPI and Ollama; deployed as a PWA for low-bandwidth access.",
    tech: ["Next.js", "FastAPI", "Ollama", "RAG", "PWA", "Tailwind"],
    cover_image: null,
    gallery: [],
    live_url: null,
    github_url: "https://github.com/prasanth-selva",
    featured: true,
    published: true,
    sort_order: 1,
    created_at: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "seed-edumentorai",
    slug: "edumentor-ai",
    title: "EduMentorAI",
    tagline: "Offline-first AI tutor for rural Tamil Nadu students",
    description:
      "EduMentorAI is an offline-capable AI tutor built for students in rural Tamil Nadu with unreliable connectivity. A FastAPI backend serves a fully local Ollama model; FAISS powers retrieval-augmented answers over the Tamil Nadu state syllabus, and a PWA shell caches lessons for zero-network study sessions. Teachers curate the corpus; students ask in Tamil or English and get syllabus-grounded explanations with citations.",
    tech: ["FastAPI", "Ollama", "FAISS", "RAG", "PWA", "React"],
    cover_image: null,
    gallery: [],
    live_url: null,
    github_url: "https://github.com/prasanth-selva",
    featured: true,
    published: true,
    sort_order: 2,
    created_at: "2025-11-02T00:00:00.000Z",
  },
  {
    id: "seed-hackastorm",
    slug: "hackastorm",
    title: "HACKASTORM",
    tagline: "AI worker-safety monitoring system — Team Cyberbots",
    description:
      "HACKASTORM is an AI worker-safety monitoring system built with Team Cyberbots for industrial floors. Computer-vision models on edge cameras detect missing PPE, unsafe proximity to machinery and fall events in real time, raising tiered alerts with on-site siren and supervisor notification. The stack pairs YOLO-based detection with a FastAPI control plane and an operator dashboard for shift analytics.",
    tech: ["Python", "YOLO", "Computer Vision", "FastAPI", "Edge AI"],
    cover_image: null,
    gallery: [],
    live_url: null,
    github_url: "https://github.com/prasanth-selva",
    featured: true,
    published: true,
    sort_order: 3,
    created_at: "2025-09-20T00:00:00.000Z",
  },
  {
    id: "seed-isc-realtors",
    slug: "isc-realtors",
    title: "ISC Realtors",
    tagline: "3D-animated luxury real-estate experience",
    description:
      "ISC Realtors is a 3D-animated luxury real-estate website for ISC PropCare. Cinematic scroll-driven scenes, property showcases with interactive floor plans and a lead pipeline are built on Next.js with WebGL-accented motion. Shipped live at iscpropcare.in with perfect Lighthouse accessibility scores.",
    tech: ["Next.js", "Three.js", "GSAP", "Tailwind", "Framer Motion"],
    cover_image: null,
    gallery: [],
    live_url: "https://iscpropcare.in",
    github_url: null,
    featured: false,
    published: true,
    sort_order: 4,
    created_at: "2025-08-10T00:00:00.000Z",
  },
];

export const SEED_EXPERIENCE: Experience[] = [
  {
    id: "seed-lunablaze",
    role: "Cyber Security Engineer Intern",
    org: "LunaBlaze",
    location: "Remote",
    start_date: "Jun 2026",
    end_date: "Jul 2026",
    current: false,
    description:
      "Engineered detection rules and ran monitoring rotations on the SOC floor. Built automated triage playbooks that cut analyst response time, hardened Linux endpoints, and produced internal threat reports adopted by the engineering team.",
    tech: ["SIEM", "IDS/IPS", "Linux", "Python"],
    sort_order: 1,
    published: true,
    created_at: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "seed-cybercrime",
    role: "Cybercrime Intern",
    org: "Coimbatore Cybercrime Police Station",
    location: "Coimbatore, India",
    start_date: "5 Jun 2026",
    end_date: "19 Jun 2026",
    current: false,
    description:
      "Assisted investigations into online fraud and social-media offences: evidence preservation, digital-trace analysis and victim interviews. Witnessed first-hand how cybercrime impacts real people — the reason I treat security as a public good.",
    tech: ["Digital Forensics", "OSINT", "Incident Reporting"],
    sort_order: 2,
    published: true,
    created_at: "2026-06-05T00:00:00.000Z",
  },
  {
    id: "seed-metazord",
    role: "Full-Stack Developer & Cybersecurity Analyst",
    org: "Metazord / House of MetaZord",
    location: "Coimbatore, India",
    start_date: "Oct 2025",
    end_date: "Apr 2026",
    current: false,
    description:
      "Split my time between the SOC and the product team: AI-based threat monitoring pipelines, network-security reviews and hardening, plus full-stack development of internal tools. Owned alert-quality metrics end to end — from rule tuning to analyst feedback loops.",
    tech: ["SOC Operations", "AI Threat Monitoring", "Network Security", "Next.js", "FastAPI"],
    sort_order: 3,
    published: true,
    created_at: "2025-10-01T00:00:00.000Z",
  },
  {
    id: "seed-vyugam",
    role: "President",
    org: "VYUGAM — Cyber Department Association",
    location: "KGISL Institute of Technology",
    start_date: "Oct 2025",
    end_date: null,
    current: true,
    description:
      "Leading the cyber department association: curating workshops, CTFs and speaker sessions for 300+ students, managing a 12-member core team, and partnering with industry mentors for hands-on security training.",
    tech: ["Leadership", "Community", "Event Operations"],
    sort_order: 4,
    published: true,
    created_at: "2025-10-01T00:00:00.000Z",
  },
];

export const SEED_SKILLS: Skill[] = [
  { id: "seed-linux", name: "Linux", category: "Core", level: 90, sort_order: 1, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-python", name: "Python", category: "Core", level: 88, sort_order: 2, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-bash", name: "Bash", category: "Core", level: 82, sort_order: 3, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-siem", name: "SIEM", category: "Defense", level: 84, sort_order: 4, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-ids-ips", name: "IDS/IPS", category: "Defense", level: 80, sort_order: 5, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-websec", name: "Web Security", category: "Offense", level: 86, sort_order: 6, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-burp", name: "Burp Suite", category: "Offense", level: 78, sort_order: 7, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-metasploit", name: "Metasploit", category: "Offense", level: 74, sort_order: 8, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-nextjs", name: "Next.js", category: "Build", level: 85, sort_order: 9, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-fastapi", name: "FastAPI", category: "Build", level: 83, sort_order: 10, published: true, created_at: "2026-01-01T00:00:00.000Z" },
  { id: "seed-ollama-rag", name: "Ollama / RAG", category: "Build", level: 80, sort_order: 11, published: true, created_at: "2026-01-01T00:00:00.000Z" },
];

export const SEED_CERTIFICATIONS: Certification[] = [
  {
    id: "seed-cert-google-cyber",
    title: "Google Cybersecurity Professional Certificate",
    issuer: "Google / Coursera",
    issued_on: "2025",
    credential_url: null,
    image: null,
    sort_order: 1,
    published: true,
    created_at: "2025-06-01T00:00:00.000Z",
  },
  {
    id: "seed-cert-cisco-eh",
    title: "Ethical Hacking (70-hour course)",
    issuer: "Cisco Networking Academy",
    issued_on: "2025",
    credential_url: null,
    image: null,
    sort_order: 2,
    published: true,
    created_at: "2025-07-01T00:00:00.000Z",
  },
  {
    id: "seed-cert-metasploit",
    title: "Metasploit for Beginners",
    issuer: "Cisco Networking Academy",
    issued_on: "2025",
    credential_url: null,
    image: null,
    sort_order: 3,
    published: true,
    created_at: "2025-08-01T00:00:00.000Z",
  },
  {
    id: "seed-cert-risk",
    title: "Google Cybersecurity: Risk Management",
    issuer: "Google / Coursera",
    issued_on: "2026",
    credential_url: null,
    image: null,
    sort_order: 4,
    published: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "seed-cert-learnsart",
    title: "Advanced Cybersecurity Course",
    issuer: "Learnsart",
    issued_on: "2026",
    credential_url: null,
    image: null,
    sort_order: 5,
    published: true,
    created_at: "2026-02-01T00:00:00.000Z",
  },
];

export const SEED_ACHIEVEMENTS: Achievement[] = [
  {
    id: "seed-ach-top50",
    title: "Top 50 nationally — CTF at Malla Reddy University",
    detail:
      "Ranked among the top 50 teams nationally at the capture-the-flag hosted during the national-level tech fest at Malla Reddy University, March 2026 — web exploitation, forensics and crypto categories.",
    occurred_on: "Mar 2026",
    image: null,
    sort_order: 1,
    published: true,
    created_at: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "seed-ach-23rd",
    title: "23rd of 450+ teams — national CTF",
    detail:
      "Secured 23rd place among 450+ teams in a national capture-the-flag, contributing web and OSINT solves under a 36-hour clock.",
    occurred_on: "2026",
    image: null,
    sort_order: 2,
    published: true,
    created_at: "2026-04-01T00:00:00.000Z",
  },
  {
    id: "seed-ach-vyugam",
    title: "President, VYUGAM Cyber Department Association",
    detail:
      "Elected president of the department's cyber association; grew event participation 3× year-over-year and launched a semester-long security bootcamp.",
    occurred_on: "Oct 2025",
    image: null,
    sort_order: 3,
    published: true,
    created_at: "2025-10-01T00:00:00.000Z",
  },
];

export const SEED_POSTS: Post[] = [
  {
    id: "seed-post-ctf-mru",
    slug: "ctf-malla-reddy-2026-writeup",
    title: "Top 50 at Malla Reddy University CTF — full writeup",
    excerpt:
      "How our team sliced through web exploitation and forensics challenges to finish top 50 nationally.",
    content: [
      "---",
      "title: Top 50 at Malla Reddy University CTF",
      "---",
      "",
      "## The setup",
      "",
      "A 36-hour clock, eight challenges on the board and a team of three running on filter coffee. Our strategy: split by category — I took web, the forensics specialist took disk images, and our crypto lead brute-solved the RSA warmups.",
      "",
      "## Web challenges",
      "",
      "The web track was classic: a `pickle` deserialization chain, a GraphQL introspection leak, and an SQLi behind a WAF that accepted `UNION/**/SELECT`.",
      "",
      "```python",
      "# Serialized payload chain (simplified)",
      "import pickle, base64",
      "",
      "class Exploit:",
      "    def __reduce__(self):",
      "        return (os.system, ('cat /flag.txt',))",
      "",
      "print(base64.b64encode(pickle.dumps(Exploit())).decode())",
      "```",
      "",
      "## Lessons",
      "",
      "- Time-box every challenge; sunk cost kills rankings.",
      "- `UNION/**/SELECT` still bypasses half the WAFs you'll meet.",
      "- Write flags to a shared doc immediately — handoffs win events.",
    ].join("\n"),
    tags: ["ctf", "web-security", "writeup"],
    cover_image: null,
    reading_minutes: 4,
    published: true,
    published_at: "2026-03-20T00:00:00.000Z",
    created_at: "2026-03-20T00:00:00.000Z",
    updated_at: "2026-03-20T00:00:00.000Z",
  },
  {
    id: "seed-post-waf-notes",
    slug: "appsec-notes-waf-bypass-patterns",
    title: "AppSec notes: five WAF bypass patterns I see every week",
    excerpt:
      "Practical patterns from real triage: comment injection, encoding tricks, parser differentials and more.",
    content: [
      "---",
      "title: AppSec notes — WAF bypass patterns",
      "---",
      "",
      "## 1. Comment injection",
      "",
      "```http",
      "GET /search?q=UNION/**/SELECT/**/password HTTP/1.1",
      "```",
      "",
      "## 2. Parser differentials",
      "",
      "When the WAF and the origin disagree about request parsing, the origin loses. Send ambiguous requests and watch which side blinks first.",
      "",
      "## 3. Overlong UTF-8",
      "",
      "Legacy decoders still normalize `%C0%AE` in surprising places.",
      "",
      "> Defense: normalize once, validate twice, and never trust the proxy's opinion of your input.",
    ].join("\n"),
    tags: ["appsec", "waf", "notes"],
    cover_image: null,
    reading_minutes: 3,
    published: true,
    published_at: "2026-05-02T00:00:00.000Z",
    created_at: "2026-05-02T00:00:00.000Z",
    updated_at: "2026-05-02T00:00:00.000Z",
  },
];
